### ISSUE TITLE
uplift/{backend,bot}: Fix exceptions

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1525]
```
# uplift/bot:
uplift_bot.sync: Failed to add bug #1486970 : Invalid response from post https://localhost:8011/bugs : b'<html>\n  <head>\n    <title>Internal Server Error</title>\n  </head>\n  <body>\n    <h1><p>Internal Server Error</p></h1>\n    \n  </body>\n</html>\n'

# came from uplift/backend:
  File "/app/src/uplift/backend/uplift_backend/api.py", line 211, in create_bug
    raise Exception('Missing uplift comment in analysis')
```

Indeed https://bugzilla.mozilla.org/show_bug.cgi?id=1486970#c27 doesn't respect the expected format. The bot seems to skip analysis entirely in this case.

```
# uplift/backend:
[2018-09-19 13:47:26 +0000] [9625] [ERROR] Error handling request /bugs/1486971/patches
Traceback (most recent call last):
  File "/nix/store/vyw6gddj1y3jh9jn1v376c1zm74ca2pm-python3.6-SQLAlchemy-1.2.10/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/nix/store/vyw6gddj1y3jh9jn1v376c1zm74ca2pm-python3.6-SQLAlchemy-1.2.10/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: operator does not exist: character varying = integer[]
LINE 3: ...' AND uplift_backend_patch_status.revision_parent = ARRAY[99...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Comment by La0** [comment]
I pushed a patch to fix the issue on bug `1486971`, i think it's an old issue (seen in sentry)

**Comment by La0** [comment]
@jankeromnes Can we close this issue now ?

**Comment by La0** [comment]
Uplifts projects are off.
