### ISSUE TITLE
staticanalysis/bot: ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1699]
Error: `ValueError: too many values to unpack (expected 2)`

Location:

https://github.com/mozilla/release-services/blob/99a13b60386e801229304e20e77892d65efedae5/src/staticanalysis/bot/static_analysis_bot/workflow.py#L213

Example Task: https://tools.taskcluster.net/groups/QfLd7Z2SQJaireYqMBnPUQ/

Full logs:

```
static_analysis_bot.workflow: Run ClangFormat
static_analysis_bot.clang.format: Running ./mach clang-format (cmd='gecko-env ./mach --log-no-times clang-format')
+ exec ./mach --log-no-times clang-format
datadog.api: 202 POST https://api.datadoghq.com/api/v1/series (320.7631ms)
static_analysis_bot.workflow: Run MozLint
datadog.api: 202 POST https://api.datadoghq.com/api/v1/series (321.8524ms)
static_analysis_bot.cli: Static analysis failure (revision=PHID-DIFF-7c3wyz42vvsz54sghexw error=ValueError('too many values to unpack (expected 2)',))
Traceback (most recent call last):
  File "/nix/store/9wp9sxhplxx9hh59xw8vi9s1ldpzcykb-python3.6-mozilla-staticanalysis-bot-1.0.0/bin/..static-analysis-bot-wrapped-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/8akzn6hhq0dg211vdabyn59hqa99l8qy-python3.6-Click-7.0/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/8akzn6hhq0dg211vdabyn59hqa99l8qy-python3.6-Click-7.0/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/8akzn6hhq0dg211vdabyn59hqa99l8qy-python3.6-Click-7.0/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/8akzn6hhq0dg211vdabyn59hqa99l8qy-python3.6-Click-7.0/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/p2v4azvgp1vphcjqzi65mv5g33fvybl1-python3.6-python3.6-mozilla-cli-common-1.0.0/lib/python3.6/site-packages/cli_common/cli.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/nix/store/bwfygfcdvis9wd1c1v51xwnwhw1hx0a0-python3-3.6.6/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/nix/store/9wp9sxhplxx9hh59xw8vi9s1ldpzcykb-python3.6-mozilla-staticanalysis-bot-1.0.0/lib/python3.6/site-packages/static_analysis_bot/cli.py", line 116, in main
    w.run(revision)
  File "/nix/store/9wp9sxhplxx9hh59xw8vi9s1ldpzcykb-python3.6-mozilla-staticanalysis-bot-1.0.0/lib/python3.6/site-packages/static_analysis_bot/workflow.py", line 213, in run
    before_patch, _ = self.detect_issues(analyzers, revision)
ValueError: too many values to unpack (expected 2)
datadog.api: 202 POST https://api.datadoghq.com/api/v1/series (353.1992ms)
[taskcluster 2018-11-23 11:43:53.077Z] === Task Finished ===
```

**Comment by jankeromnes** [comment]
Seems to have been introduced by mistake in https://github.com/mozilla/release-services/commit/002aed148b8d3be3d3b59af0bbc96c8390e2bd06#diff-2458bd47d8d17abd9f62fcde5af69d2eR213
