### ISSUE TITLE
staticanalysis/bot: Failed to import target patch: uncommitted changes after clang-format analysis

### ISSUE THREAD

**Issue by jankeromnes** [mozilla/release-services#1701]
From Task https://tools.taskcluster.net/groups/J_hyznxKSYS-bALG1UbuKw/ :

```
static_analysis_bot.workflow: Run ClangFormat
static_analysis_bot.clang.format: Running ./mach clang-format (cmd='gecko-env ./mach --log-no-times clang-format')
+ exec ./mach --log-no-times clang-format
datadog.api: 202 POST https://api.datadoghq.com/api/v1/series (324.3423ms)
static_analysis_bot.revisions: Improvement patch saved (path='/tmp/results/clang-format-PHID-DIFF-pnsoon5g5tjkwuq2avhv.diff' length=10311)
static_analysis_bot.workflow: Run MozLint
static_analysis_bot.workflow: Detected 235 issue(s) before patch
static_analysis_bot.cli: Static analysis failure (revision=PHID-DIFF-pnsoon5g5tjkwuq2avhv error=AnalysisException('Failed to import target patch',))
Traceback (most recent call last):
  File "/nix/store/db3w4x32mqszxl6dxzl8n8ryj62zidy6-python3.6-mozilla-staticanalysis-bot-1.0.0/lib/python3.6/site-packages/static_analysis_bot/revisions.py", line 258, in apply
    user='reviewbot',
  File "/nix/store/51makg8fn7k200fz3phm54pa61mja4jw-python3.6-python-hglib-2.6.1/lib/python3.6/site-packages/hglib/client.py", line 996, in import_
    self.rawcommand(args, prompt=prompt, input=input)
  File "/nix/store/51makg8fn7k200fz3phm54pa61mja4jw-python3.6-python-hglib-2.6.1/lib/python3.6/site-packages/hglib/client.py", line 263, in rawcommand
    raise error.CommandError(args, ret, out, err)
hglib.error.CommandError: (255, b'', b'abort: uncommitted changes')
```

**Comment by jankeromnes** [comment]
I think the solution would be to clean up the repository state after the `before` analysis, so that the `after` analysis can start with the same conditions.

**Comment by jankeromnes** [comment]
Blocks #1236
