### ISSUE TITLE
Try to reconnect automatically to pulse server

### ISSUE THREAD

**Issue by La0** [mozilla/release-services#827]
The pulse server was shutdown on 2018-02-07, and pulse listener just stopped working, not trying to reconnect after the server went back up.

Error message in log:
```
aioamqp.protocol: Server closed connection: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', code=320, class_id=0, method_id=0
```

**Comment by marco-c** [comment]
The code coverage hook stopped receiving messages suddenly on 2018-02-15 at 5 PM. I've restarted the pulse listener today and it's getting all the messages which weren't received before (they were probably in the pulse queue).
So maybe it can also happen that the pulse listener gets disconnected from the pulse queue.

**Comment by marco-c** [comment]
Here's the likely culprit:
```
2018-02-15T17:08:18.043139+00:00 app[worker.1]: aioamqp.protocol: error on dispatch
2018-02-15T17:08:18.043155+00:00 app[worker.1]: Traceback (most recent call last):
2018-02-15T17:08:18.043161+00:00 app[worker.1]:   File "/nix/store/kdslnps7fv23h2902q234jqqmacpm0hv-python3.5-aioamqp-0.10.0/lib/python3.5/site-packages/aioamqp/protocol.py", line 333, in run
2018-02-15T17:08:18.043162+00:00 app[worker.1]:     yield from self.dispatch_frame()
2018-02-15T17:08:18.043167+00:00 app[worker.1]:   File "/nix/store/kdslnps7fv23h2902q234jqqmacpm0hv-python3.5-aioamqp-0.10.0/lib/python3.5/site-packages/aioamqp/protocol.py", line 288, in dispatch_frame
2018-02-15T17:08:18.043169+00:00 app[worker.1]:     yield from channel.dispatch_frame(frame)
2018-02-15T17:08:18.043170+00:00 app[worker.1]:   File "/nix/store/kdslnps7fv23h2902q234jqqmacpm0hv-python3.5-aioamqp-0.10.0/lib/python3.5/site-packages/aioamqp/channel.py", line 107, in dispatch_frame
2018-02-15T17:08:18.043173+00:00 app[worker.1]:     yield from methods[(frame.class_id, frame.method_id)](frame)
2018-02-15T17:08:18.043174+00:00 app[worker.1]:   File "/nix/store/kdslnps7fv23h2902q234jqqmacpm0hv-python3.5-aioamqp-0.10.0/lib/python3.5/site-packages/aioamqp/channel.py", line 641, in basic_deliver
2018-02-15T17:08:18.043176+00:00 app[worker.1]:     yield from callback(self, body, envelope, properties)
2018-02-15T17:08:18.043179+00:00 app[worker.1]:   File "/nix/store/zxh636rx9q20hm6ypzc5x42kmhrwj2n7-mozilla-shipit-pulse-listener-1.0.0/lib/python3.5/site-packages/shipit_pulse_listener/hook.py", line 137, in got_message
2018-02-15T17:08:18.043181+00:00 app[worker.1]:     env = self.parse(body)
2018-02-15T17:08:18.043183+00:00 app[worker.1]:   File "/nix/store/zxh636rx9q20hm6ypzc5x42kmhrwj2n7-mozilla-shipit-pulse-listener-1.0.0/lib/python3.5/site-packages/shipit_pulse_listener/listener.py", line 279, in parse
2018-02-15T17:08:18.043185+00:00 app[worker.1]:     build_task = self.get_build_task_in_group(taskGroupId)
2018-02-15T17:08:18.043187+00:00 app[worker.1]:   File "/nix/store/zxh636rx9q20hm6ypzc5x42kmhrwj2n7-mozilla-shipit-pulse-listener-1.0.0/lib/python3.5/site-packages/shipit_pulse_listener/listener.py", line 268, in get_build_task_in_group
2018-02-15T17:08:18.043189+00:00 app[worker.1]:     reply = r.json()
2018-02-15T17:08:18.043190+00:00 app[worker.1]:   File "/nix/store/kgyzdnywnbd7174wbwp4y60sn1n9ml9a-python3.5-requests-2.18.3/lib/python3.5/site-packages/requests/models.py", line 892, in json
2018-02-15T17:08:18.043192+00:00 app[worker.1]:     return complexjson.loads(self.text, **kwargs)
2018-02-15T17:08:18.043194+00:00 app[worker.1]:   File "/nix/store/r8prjv40r8z2pl4sc8j343rp6mhs0mkj-python3-3.5.4/lib/python3.5/json/__init__.py", line 319, in loads
2018-02-15T17:08:18.043196+00:00 app[worker.1]:     return _default_decoder.decode(s)
2018-02-15T17:08:18.043197+00:00 app[worker.1]:   File "/nix/store/r8prjv40r8z2pl4sc8j343rp6mhs0mkj-python3-3.5.4/lib/python3.5/json/decoder.py", line 339, in decode
2018-02-15T17:08:18.043199+00:00 app[worker.1]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2018-02-15T17:08:18.043201+00:00 app[worker.1]:   File "/nix/store/r8prjv40r8z2pl4sc8j343rp6mhs0mkj-python3-3.5.4/lib/python3.5/json/decoder.py", line 355, in raw_decode
2018-02-15T17:08:18.043202+00:00 app[worker.1]:     obj, end = self.scan_once(s, idx)
2018-02-15T17:08:18.043204+00:00 app[worker.1]: json.decoder.JSONDecodeError: Unterminated string starting at: line 21556 column 24 (char 853648)
```

**Comment by marco-c** [comment]
So it's a request that failed in the code coverage hook, I'll file a separate issue.

**Comment by rail** [comment]
Happened to the shipitapi worker as well... :/

**Comment by rail** [comment]
See also:
https://github.com/Polyconseil/aioamqp/issues/65
https://github.com/Polyconseil/aioamqp/issues/144

**Comment by garbas** [comment]
is this something we could implement in cli_common.pulse and be able to reuse it? it looks like a pretty common case
